var _lang_pack = {
	"common_check_blank":"입력해주세요.",
	"common_no_selected":"선택할 항목이 없습니다.",
	"common_number_only":"숫자만 입력하셔야 합니다.",
	"common_input_mtype":"개인/기업회원 여부를 입력해주세요.",
	"common_input_memberid":"회원 아이디를 입력해주세요.",
	"common_input_pwd":"비밀번호를 입력해주세요.",
	"common_input_ono":"주문번호를 입력해주세요",
	"common_input_phonenum":"전화번호를 입력해주세요",
	"common_confirm_login":"로그인이 필요한 서비스입니다.\n로그인 하시겠습니까?",
	"common_need_login":"로그인해주세요.",
	"common_input_searchstr":"검색어를 입력해주세요.",
	"common_recentprd_last":"최근 본 상품의 마지막 상품입니다.",
	"common_recentprd_first":"최근 본 상품의 첫번째 상품입니다",
	"common_input_name":"이름을 입력해주세요.",
	"common_input_email":"이메일 주소를 입력해주세요.",
	"common_wrong_email":"이메일 형식이 유효하지 않습니다.",
	"common_input_subject":"제목을 입력해주세요.",
	"common_input_content":"내용을 입력해주세요.",
	"common_input_cate":"분류를 선택해주세요.",
	"common_input_agree":"개인정보 수집 및 이용에 동의해주세요.",
	"common_blocked_popup":"브라우저의 새창열기가 차단되어있습니다.\n새창열기를 활성화 해주세요.",
	"common_input_scnum":"소셜쿠폰번호를 입력해주세요.",
	"common_confirm_delete":"삭제하시겠습니까?",
	"common_faild_fdelete":"파일 삭제가 실패되었습니다.",
	"common_last_page":"마지막 페이지입니다.",
	"common_confirm_wishlist":"위시리스트로 이동하시겠습니까?",
	"common_restore_sleep":"휴면상태의 아이디입니다.\n휴면상태를 해제하시겠습니까?",
	"common_input_addinfo":"추가정보({0})를 입력해주세요.",
	"common_info_recertnum":"인증번호 재발송",
	"common_info_certcomplete":"인증이 완료되었습니다.",
	"common_error_illegalConn__":"비정상적인 접속입니다",
	"common_save_setting":"설정이 저장되었습니다.",
	"common_add_favorite":"확인을 클릭하신 후 주소창에서 <Ctrl+D>를 누르시면 즐겨찾기에 등록됩니다.",
	"common_info_today":"오늘",
	"coommon_info_close":"닫기",
	"common_bookmark_function":"이 브라우저에서는 즐겨찾기 기능을 사용할 수 없습니다.\nCtrl 키와 D 키를 동시에 눌러서 즐겨찾기에 추가할 수 있습니다.",
	"data_week_sun":"일", 
	"data_week_mon":"월", 
	"data_week_tue":"화",
	"data_week_wed":"수",
	"data_week_thu":"목",
	"data_week_fri":"금",
	"data_week_sat":"토",

	"member_confirm_agree1":"이용약관에 동의해주세요.",
	"member_confirm_agree2":"개인정보 수집 및 이용에 동의해주세요.",
	"member_confirm_joincert":"가입인증을 진행해주세요.",
	"member_info_memberid1":"아이디를 공백없이 영문, 숫자로 입력해주세요.",
	"member_info_memberid2":"아이디는 4~16자 이내로 입력해 주십시오.",
	"member_info_memberid3":"아이디에는 최소 1개 이상의 영문 소문자가 포함되어야 합니다.",
	"member_info_memberid4":"아이디에는 대문자를 입력할 수 없습니다.",
	"member_input_nickname":"닉네임을 입력해주세요.",
	"member_input_contactname":"부서명 이름을 입력해주세요.",	// [커스텀] 담당자명 -> 부서명
	"member_input_owner":"회사명 이름을 입력해주세요.",			// [커스텀] 대표자명 -> 회사명
	"member_input_company":"회사명을 입력해주세요.",
	"member_input_biznum":"사업자 등록번호를 입력해주세요.",
	"member_info_biznum":"사업자 등록번호는 숫자만 입력할수 있습니다.",
	"member_wrong_biznum":"사업자 등록번호가 잘못되었습니다.",
	"member_input_jobtype1":"업태를 입력해주세요.",
	"member_input_jobtype2":"업종을 입력해주세요.",
	"member_check_memberid":"아이디 중복체크를 진행해주세요.",
	"member_input_gender":"성별을 입력해주세요.",
	"member_input_birth1":"생년월일(년)을 입력해 주세요.",
	"member_input_birth2":"생년월일(월)을 입력해 주세요.",
	"member_input_birth3":"생년월일(일)을 입력해 주세요.",
	"member_info_pwd1":"비밀번호는 {0}자 이상 입력해주세요.",
	"member_info_pwd2":"비밀번호에는 영문,숫자,특수기호만 사용할 수 있습니다.",
	"member_input_cpwd":"확인 비밀번호를 입력해주세요.",
	"member_error_cpwd":"비밀번호와 확인 비밀번호가 다릅니다.",
	"member_input_phone":"전화번호를 입력해주세요.",
	"member_input_cell":"휴대폰번호를 입력해주세요.",
	"member_wrong_cell":"잘못된 휴대전화 번호입니다.\n번호를 확인한 다음 다시 입력해 주세요.",
	"member_error_phone":"전화번호는 숫자만 입력가능합니다.",
	"member_error_cell":"휴대폰번호는 숫자만 입력가능합니다.",
	"member_input_zipcode":"우편번호를 입력해주세요.",
	"member_input_addr1":"주소를 입력해주세요",
	"member_input_addr2":"나머지 상세 주소를 입력해주세요",
	"member_info_chgemail":"이메일이 변경되었습니다.",
	"member_info_chgauth":"개인확인방법이 변경되었습니다.",
	"member_confirm_cert":"인증메일을 받으신 후 인증을 완료하셔야 정상 이용이 가능합니다.\n계속 진행하시겠습니까?",
	"member_input_rejectreason":"탈퇴사유를 입력해주세요.",
	"member_input_certnum":"인증번호를 입력해주세요.",
	"member_info_skin":"스킨 정보를 확인해 주세요.",
	"member_idpwd_confirm_sent":"인증번호가 발송되었습니다.",
	"member_idpwd_input_sent":"발송된 인증번호를 입력해주세요.",
	"member_idpwd_reg_code":"인증번호가 일치하지 않습니다.",
	"member_idpwd_reg_code_expired":"인증번호 유효시간이 초과되었습니다.",
	"member_join_14_limit":"만 14세 미만의 아동은 회원가입이 불가능합니다.",
	"order_info_guestorder":"비회원 개인정보 수집 및 이용 동의 시 주문이 가능합니다.",
	"order_input_buyer":"주문하시는분 이름을 입력해 주세요",
	"order_input_number":"주문하시는 분 전화 번호나 휴대전화 번호를 공백없이 숫자로 입력해주세요.",
	"order_input_phone":"주문하시는 분 전화 번호를 공백없이 숫자로 입력해주세요.",
	"order_input_cell":"주문하시는 분 휴대전화 번호를 공백없이 숫자로 입력해주세요.",
	"order_input_zipcode":"주문하시는 분 우편번호를 입력해주세요.",
	"order_input_addr1":"주문하시는 분 주소를 입력해주세요.",
	"order_input_addr2":"주문하시는 분 나머지 상세주소를 입력해주세요.",
	"order_input_email":"주문하시는 분 이메일주소를 입력해주세요.",
	"order_wrong_email":"주문하시는 분 이메일 형식이 정확하지 않습니다.",
	"order_input_rname":"받으실 분 이름을 입력해주세요.",
	"order_input_rnumber":"받으실 분 전화번호나 휴대전화번호를 공백없이 숫자로 입력하세요.",
	"order_input_rphone":"받으실 분 전화 번호를 공백없이 숫자로 입력하세요.",
	"order_input_rcell":"받으실 분 휴대전화 번호를 공백없이 숫자로 입력하세요.",
	"order_input_rzipcode":"배송지 우편번호를 입력해주세요.",
	"order_input_raddr1":"배송지 주소를 입력해주세요.",
	"order_input_raddr2":"배송지 상세주소를 입력해주세요.",
	"order_select_paytype":"결제방식을 선택해주세요.",
	'order_input_bank':'입금 은행을 선택해주세요.',
	"order_input_depositor":"무통장 입금자명을 입력해주세요.",
	"order_error_escrow":"실 결제금액({0}"+currency+")이 {1}"+currency+" 이하이므로 에스크로 서비스를 사용할 수 없습니다.",
	"order_error_usablemileage":"사용가능한 적립금은 {0}"+currency+" 이하입니다.",
	"order_error_usableemoney":"사용가능한 예치금은 {0}"+currency+" 이하입니다.",
	"order_info_pgup":"해당 결제방식 이용시 상품금액의 {0}% 가 인상됩니다",
	"order_service_freedelivery":"무료배송이벤트",
	"order_service_mfreedelivery":"회원무료배송",
	"order_error_overpoint":"총 결제 금액보다 적립금과 예치금의 결제 금액이 더 큽니다.",
	"order_error_overmileage":"총 결제 금액보다 적립금의 결제 금액이 더 큽니다.",
	"order_error_overemoney":"총 결제 금액보다 예치금의 결제 금액이 더 큽니다.",
	"order_info_freedelivery":"무료",
	"order_service_setsale":"세트할인",
	"order_service_eventsale":"이벤트할인",
	"order_service_timesale":"타임세일",
	"order_service_msale":"회원할인",
	"order_service_mmileage":"회원적립금",
	"order_service_emileage":"이벤트적립금",
	"order_service_cpnsale":"쿠폰할인",
	"order_service_prcsale":"주문상품금액할인",
	"order_error_cpnuse1":"쿠폰 사용 시 적립금 적립이 되지 않습니다.",
	"order_error_cpnuse2":"{0}"+currency+"이상 구매하셔야 사용할 수 있습니다",
	"order_error_cpnuse3":"무료배송시에는 사용하실 수 없습니다.",
	"order_error_cpnuse4":"할인상품과 함께 구매하시면 쿠폰을 사용하실 수 없습니다.",
	"order_error_cpnuse5":"쿠폰이 적용 가능한 상품을 {0}"+currency+" 이상 구매 하셔야 쿠폰을 사용 하실 수 있습니다.",
	"order_error_cpnuse6":"총 {0}"+currency+"이상 구매하셔야 쿠폰을 사용할 수 있습니다.",
	"order_error_cpnuse7":"선택하신 쿠폰으로 할인 가능한 상품이 없습니다.",
	"order_error_cpnuse8":"총 할인 대상 상품합계가 쿠폰 할인액보다 작습니다.",
	"order_error_offcpn1":"무통장입금 결제시에만 사용가능합니다",
	"order_error_offcpn2":"쿠폰 인증코드를 입력해주세요.",
	"order_error_offcpn3":"최대 {0}"+currency+"까지 할인이 가능합니다.",
	"order_error_offcpn4":"할인상품과 함께 구매하시면 쿠폰을 사용하실 수 없습니다.",
	"order_error_prdcpn_paytype":"무통장입금 전용 쿠폰입니다. 주문서 페이지에서 무통장입금 결제 시 사용 가능합니다.",
	"order_confirm_offcpn":"쿠폰을 적용하시겠습니까?\n온라인 쿠폰과는 중복사용이 불가능합니다.",
	"order_info_offcpn":"적용됨",
	"order_confirm_cpncancel":"해당 쿠폰의 사용을 취소하시겠습니까?",
	"order_select_gift":"사은품을 선택해주세요.",
	"order_service_dtype1":"배송비할인",
	"order_service_dtype2":"배송비추가",
	"order_service_dtype3":"지역별 배송비",
	"order_select_nations":"배송국가를 선택하세요.",
	"order_select_delivery_com":"배송업체를 선택하세요.",
	"order_reconfirm_checked":"결제정보 확인 및 구매진행에 동의하셔야 주문이 가능합니다.",
	"order_coupon_milage":"쿠폰 사용 시 적립금 사용이 불가능합니다.\n쿠폰을 사용하시겠습니까?",

	"shop_error_soldout":"품절된 상품은 주문하실 수 없습니다.",
	"shop_error_minord":"이 상품은 최소 {0}개 이상 구매하셔야 합니다.",
	"shop_error_maxord":"이 상품은 최대 {0}개 까지 구매하실수 있습니다.",
	"shop_error_optionset1":"{0} 옵션을 선택해주세요.",
	"shop_error_optionset2":"{0} 옵션의 {1}을 입력해 주세요.",
	"shop_error_optionset3":"{0} 옵션을 입력해주세요.",
	"shop_error_optionsoldout":"{0} 옵션은 품절되었습니다.",
	"shop_error_optionmaxord":"{0} 옵션은 {1}개 까지만 구매하실수 있습니다.",
	"shop_confirm_cart":"장바구니에 있는 상품과 함께 주문하시겠습니까?\n취소를 클릭하시면 선택하신 상품만 주문됩니다.",
	"shop_error_nowishlist":"위시리스트가 비었습니다",
	"shop_select_selwishlist":"위시리스트에 담을 상품을 하나 이상 선택해주세요.",
	"shop_select_rmwishlist":"위시리스트에서 삭제할 상품을 선택해주세요.",
	"shop_confirm_rmwishlist":"선택한 상품을 위시리스트에서 삭제하시겠습니까?",
	"shop_select_selcart":"장바구니에 담을 상품을 하나 이상 선택해주세요.",
	"shop_confirm_cartok":"장바구니에 추가하였습니다.\n장바구니로 이동하시겠습니까?",
	"shop_error_nocart":"장바구니가 비었습니다",
	"shop_error_nocart2":"장바구니에 구매할 상품이 없습니다.",
	"shop_select_rmcart":"장바구니에서 삭제할 상품을 선택해주세요.",
	"shop_confirm_rmcart":"선택한 상품을 장바구니에서 삭제하시겠습니까?",
	"shop_confirm_truncatecart":"장바구니를 모두 비우시겠습니까?",
	"shop_error_noprd":"구매할 상품을 하나 이상 선택해주세요.",
	"shop_input_revpts1":"상품의 평점을 선택해주세요.",
	"shop_input_revpts2":"평점을 선택해주세요.",
	"shop_error_titlen":"제목은 {0}자 이상 입력하셔야 합니다.",
	"shop_error_content":"내용은 {0}자 이상 입력하셔야 합니다.",
	"shop_error_revwp":"주문이 배송완료된 이후부터 구매후기를 작성할 수 있습니다.",
	"shop_error_secondReview":"이미 해당 상품의 후기를 작성하셨습니다.",
	"shop_confirm_rmadmin":"현재 쇼핑몰 관리자로 로그인중이므로 바로 삭제됩니다.",
	"shop_error_outprd":"현재 판매중인 상품이 아닙니다.",
	"shop_error_cancel":"취소/환불/반품 접수중입니다.",
	"shop_error_dlvafter":"반품 신청은 배송후에 가능합니다\n주문 취소 신청해주세요.",
	"shop_error_dlvbefore":"주문 취소는 배송전에 가능합니다.\n반품 신청해주세요.",
	"shop_error_counsel":"1:1 친절 상담은 이메일 주소를 입력하셔야 답변을 받으실 수 있습니다.",
	"shop_info_answerready":"현재 답변 준비중입니다.\n확인후 신속히 답변드리겠습니다.",
	"shop_confirm_downCpn":"쿠폰을 다운로드 받으시겠습니까?",
	"shop_input_buyea":"구매수량을 입력해주세요",
	"shop_confirm_complete":"상품을 받으셨나요?\n상품을 받으셨다면 \"확인\" 버튼을 눌러주세요.",
	"shop_error_selected":"이미 선택된 옵션입니다.",
	"shop_naverpay_disabled":"네이버 페이로 구매가 불가한 상품입니다.",
	"shop_naverpay_soldout":"재고가 부족하여 네이버 페이로 구매하실 수 없습니다.",
	"shop_naverpay_error":"네이버페이 구매 에러입니다.",

	"pg_error_install":"전자결제를 위한 결제모듈이 설치되지 않았습니다.",
	"pg_error_cancel":"사용자가 결제를 취소하였습니다.",
	"pg_error_popup":"팝업창 차단을 해제하셔야 결제가 가능합니다.",
	"pg_error_faild":"결제가 실패되었습니다.",
	"pg_error_cert":"인증이 실패되었습니다.",

	"member_info_findid":"회원님의 아이디는 [{0}] 입니다",
	"member_info_certcomplete":"인증이 확인되었습니다.\n비밀번호를 변경 페이지로 이동합니다.",

	"member_error_pwdminlen":"비밀번호를 4자이상 입력하세요.",

	"mypage_input_transmileage":"전환할 적립금을 입력해주세요.",
	"mypage_error_transmileage":"전환가능한 적립금을 초과하였습니다.",
	"mypage_error_moremileage":"전환하기 위해서는 더 많은 적립금이 필요합니다.",
	"mypage_confirm_transmileage":"적립금을 포인트로 전환하시겠습니까?",

	"mypage_input_transpts":"전환할 포인트를 입력해주세요.",
	"mypage_error_transpts":"전환가능한 포인트를 초과하였습니다.",
	"mypage_error_morepts":"전환하기 위해서는 더 많은 포인트가 필요합니다.",
	"mypage_confirm_transpts":"포인트를 적립금으로 전환하시겠습니까?",

	"mypage_confirm_counsel_reg":"신청하시겠습니까?",
	
	"mypage_confirm_direct_cancel":"해당 주문건을 취소하시겠습니까?",

	"order_error_nopoint":"보유포인트가 부족합니다.",

	"vote_select_item":"항목을 선택해주세요.",

	"board_info_vote":"평가 하시려면 로그인하셔야합니다.",
	"board_confirm_vote":"평가하시겠습니까?",
	"board_input_dbname":"DB명을 입력해주세요.",
	"board_confirm_rmdb":"선택한 게시판을 삭제하시겠습니까?\n게시물이 많을 경우 삭제시간이 지연될수 있습니다.",
	"board_capcha_connot":"스팸 자동생성방지를 진행해주세요.",
	"delivery_impossible_msg":"배송불가한 국가 입니다.",
	"delivery_overweight_msg":"배송 가능 무게를 초과하였습니다.",
	"join_shop_agree1":"개인정보 수집 및 이용에 동의해주세요.",
	"join_shop_agree2":"유의사항을 확인 후 동의해주세요.",
	"join_shop_agree3":"등록하는 제안 내용에 대한 제안자의 영업기밀과 관련된 정보에 대해 동의해주세요.",
	"order_no_tax_msg":"해당 국가의 상황에 따라 통관시 관세나 부가세가 부과 될수 있습니다.",
	"board_error_maxref":"관련상품은 10개까지 선택 가능합니다.",

	// 재입고 알림 관련
	"notify_restock_select_parent_option":"상위 옵션을 선택해 주세요.",
	"notify_restock_confirm_cancel":"재입고 알림 신청을 취소 하시겠습니까?",
	"notify_restock_cancel":"재입고 알림 신청을 취소했습니다."
};